# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Services_Dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1433, 723)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(210, 110, 571, 211))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.simpleSimLabel = QtGui.QLabel(self.frame)
        self.simpleSimLabel.setGeometry(QtCore.QRect(10, 0, 301, 211))
        self.simpleSimLabel.setText(_fromUtf8(""))
        self.simpleSimLabel.setPixmap(QtGui.QPixmap(_fromUtf8("../../Documents/insuranc.jpg")))
        self.simpleSimLabel.setObjectName(_fromUtf8("simpleSimLabel"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(340, 20, 231, 141))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(570, 30, 401, 61))
        self.label.setObjectName(_fromUtf8("label"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(800, 110, 591, 211))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.pushButton = QtGui.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(310, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(300, -10, 271, 171))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 281, 161))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8("../../Documents/insurance image8.jpg")))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(210, 350, 571, 211))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(330, 20, 241, 121))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton_3 = QtGui.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 170, 231, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 15, 301, 181))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8("../../Documents/insurance image7.jpg")))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(10, 40, 181, 591))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.pushButton_4 = QtGui.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 20, 141, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.frame_4)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.frame_4)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 150, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 290, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 360, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 500, 141, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.frame_4)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 430, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(800, 350, 591, 211))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.pushButton_12 = QtGui.QPushButton(self.frame_5)
        self.pushButton_12.setGeometry(QtCore.QRect(320, 170, 221, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.label_8 = QtGui.QLabel(self.frame_5)
        self.label_8.setGeometry(QtCore.QRect(310, 20, 231, 111))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(5, 30, 271, 141))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Book Antiqua"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setPixmap(QtGui.QPixmap(_fromUtf8("../../Documents/insurance image2.jpg")))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1433, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName(_fromUtf8("menuWindows"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSave_all = QtGui.QAction(MainWindow)
        self.actionSave_all.setObjectName(_fromUtf8("actionSave_all"))
        self.actionIndent_Here = QtGui.QAction(MainWindow)
        self.actionIndent_Here.setObjectName(_fromUtf8("actionIndent_Here"))
        self.actionDedent_here = QtGui.QAction(MainWindow)
        self.actionDedent_here.setObjectName(_fromUtf8("actionDedent_here"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.actionSave_all)
        self.menuEdit.addAction(self.actionIndent_Here)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDedent_here)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton_2.setText(_translate("MainWindow", "Simple Simulation", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">Here, the patient does not take</span></p><p><span style=\" font-size:12pt; color:#0000ff;\">any drugs and the viruses</span></p><p><span style=\" font-size:12pt; color:#0000ff;\">do not acquire resistance to </span></p><p><span style=\" font-size:12pt; color:#0000ff;\">drugs</span></p></body></html>", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#0000ff;\">RESEARCH SERVICES</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#0000ff;\">Below are some of our services.</span></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; text-decoration: underline; color:#0000ff;\">You can find more services at the services tab</span></p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "Simulation with drug", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">Here, we consider the effects of both </span></p><p><span style=\" font-size:12pt; color:#0000ff;\">administering drugs to the patient</span></p><p><span style=\" font-size:12pt; color:#0000ff;\">and the ability of virus particle </span></p><p><span style=\" font-size:12pt; color:#0000ff;\">offspring to inherit or mutate.</span></p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#0000ff;\">Here,we explore the effect ofdelaying </span></p><p><span style=\" font-size:12pt; font-style:italic; color:#0000ff;\">treatment on the ability of the </span></p><p><span style=\" font-size:12pt; font-style:italic; color:#0000ff;\">drug to eradicate the virus </span></p><p><span style=\" font-size:12pt; font-style:italic; color:#0000ff;\">population.</span></p></body></html>", None))
        self.pushButton_3.setText(_translate("MainWindow", "Delayed Treatment", None))
        self.pushButton_4.setText(_translate("MainWindow", "Welcome", None))
        self.pushButton_5.setText(_translate("MainWindow", "Sign in", None))
        self.pushButton_6.setText(_translate("MainWindow", "Simple Sim", None))
        self.pushButton_7.setText(_translate("MainWindow", "SimDrug", None))
        self.pushButton_8.setText(_translate("MainWindow", "DelayedTreat", None))
        self.pushButton_9.setText(_translate("MainWindow", "TwoDrugs", None))
        self.pushButton_10.setText(_translate("MainWindow", "Exit", None))
        self.pushButton_11.setText(_translate("MainWindow", "Log out", None))
        self.pushButton_12.setText(_translate("MainWindow", "2 independent drugs", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0000ff;\">Here,we use two </span></p><p><span style=\" font-size:12pt; color:#0000ff;\">independently-acting </span></p><p><span style=\" font-size:12pt; color:#0000ff;\">drugs to treat the virus.</span></p></body></html>", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Options", None))
        self.menuWindows.setTitle(_translate("MainWindow", "Windows", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionSave_all.setText(_translate("MainWindow", "Save all", None))
        self.actionIndent_Here.setText(_translate("MainWindow", "Indent Here", None))
        self.actionDedent_here.setText(_translate("MainWindow", "Dedent here", None))

